# Generated by Django 4.2.1 on 2023-06-25 19:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome_jogador', models.CharField(default='', max_length=50, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve conter apenas números, hífens (-) e espaços.', regex='^[0-9\\- ]*$')])),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='main/foto_jogador')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('uf_nascimento', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, null=True)),
                ('cidade_nascimento', models.CharField(blank=True, max_length=50, null=True)),
                ('posicao', models.CharField(choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral', 'Lateral'), ('volante', 'Volante'), ('meia', 'Meia'), ('ponta', 'Ponta'), ('centroavante', 'Centroavante')], max_length=50)),
                ('time_coracao', models.CharField(blank=True, choices=[('gremio', 'Grêmio'), ('santos', 'Santos'), ('cruzeiro', 'Cruzeiro'), ('palmeiras', 'Palmeiras'), ('atletico_mineiro', 'Atlético Mineiro'), ('botafogo', 'Botafogo'), ('flamengo', 'Flamengo'), ('fluminense', 'Fluminense'), ('internacional', 'Internacional'), ('sao_paulo', 'São Paulo'), ('vasco_da_gama', 'Vasco da Gama'), ('corinthians', 'Corinthians'), ('bahia', 'Bahia'), ('athletico_paranaense', 'Athletico Paranaense'), ('sport', 'Sport'), ('goias', 'Goiás'), ('coritiba', 'Coritiba'), ('vitoria', 'Vitória'), ('portuguesa', 'Portuguesa'), ('nautico', 'Náutico'), ('guarani', 'Guarani'), ('paysandu', 'Paysandu'), ('ceara', 'Ceará'), ('santa_cruz', 'Santa Cruz'), ('ponte_preta', 'Ponte Preta'), ('fortaleza', 'Fortaleza'), ('csa', 'CSA'), ('america_rj', 'America-RJ'), ('america_mineiro', 'América Mineiro'), ('figueirense', 'Figueirense'), ('juventude', 'Juventude'), ('remo', 'Remo'), ('parana', 'Paraná'), ('nacional_am', 'Nacional-AM'), ('america_rn', 'América-RN'), ('desportiva_ferroviaria', 'Desportiva Ferroviária-ES'), ('abc', 'ABC'), ('criciuma', 'Criciúma'), ('joinville', 'Joinville'), ('sampaio_correa', 'Sampaio Corrêa'), ('atletico_goianiense', 'Atlético Goianiense'), ('sergipe', 'Sergipe'), ('rio_branco_es', 'Rio Branco-ES'), ('crb', 'CRB'), ('bragantino', 'Bragantino'), ('moto_club', 'Moto Club'), ('bangu', 'Bangu'), ('campinense', 'Campinense'), ('avai', 'Avaí'), ('operario_ms', 'Operário-MS'), ('vila_nova', 'Vila Nova'), ('treze', 'Treze'), ('chapecoense', 'Chapecoense'), ('americano_rj', 'Americano-RJ'), ('confianca', 'Confiança'), ('river_pi', 'River-PI'), ('mixto_mt', 'Mixto-MT'), ('londrina', 'Londrina'), ('sao_caetano_sp', 'São Caetano-SP'), ('rio_negro_am', 'Rio Negro-AM'), ('botafogo_pb', 'Botafogo-PB'), ('flamengo_pi', 'Flamengo-PI'), ('inter_de_limeira', 'Inter de Limeira'), ('brasilia', 'Brasília'), ('botafogo_sp', 'Botafogo-SP'), ('gama', 'Gama'), ('ferroviario_ce', 'Ferroviário-CE'), ('gremio_maringa', 'Grêmio Maringá'), ('uberaba_mg', 'Uberaba-MG'), ('goytacaz_rj', 'Goytacaz-RJ'), ('comercial_ms', 'Comercial-MS'), ('itabaiana_se', 'Itabaiana-SE'), ('tiradentes_pi', 'Tiradentes-PI'), ('tuna_luso', 'Tuna Luso'), ('anapolina', 'Anapolina'), ('caxias_do_sul', 'Caxias do Sul'), ('brasil_de_pelotas', 'Brasil de Pelotas'), ('uniao_sao_joao_sp', 'União São João-SP'), ('uberlandia', 'Uberlândia'), ('fluminense_de_feira', 'Fluminense de Feira'), ('ceov_mt', 'CEOV-MT'), ('goiania', 'Goiânia'), ('piaui', 'Piauí'), ('xv_de_piracicaba', 'XV de Piracicaba'), ('volta_redonda', 'Volta Redonda'), ('maranhao', 'Maranhão'), ('leonico_ba', 'Leônico-BA'), ('villa_nova_mg', 'Villa Nova-MG'), ('fast_clube_am', 'Fast Clube-AM'), ('alecrim_rn', 'Alecrim-RN'), ('sao_paulo_rs', 'São Paulo-RS'), ('dom_bosco_mt', 'Dom Bosco-MT'), ('ceub_df', 'CEUB-DF'), ('ferroviario_pr', 'Ferroviário-PR'), ('fonseca_rj', 'Fonseca-RJ'), ('rabello_df', 'Rabello-DF'), ('central_pe', 'Central-PE'), ('santo_andre', 'Santo André'), ('america_sp', 'América-SP'), ('campo_grande_rj', 'Campo Grande-RJ'), ('gremio_barueri', 'Grêmio Barueri'), ('pinheiros_pr', 'Pinheiros-PR'), ('sao_jose_sp', 'São José-SP'), ('itabuna_ba', 'Itabuna-BA'), ('comercial_sp', 'Comercial-SP'), ('glicia_ba', 'Galícia-BA'), ('capelense_al', 'Capelense-AL'), ('olaria_rj', 'Olaria-RJ'), ('xv_de_jau', 'XV de Jaú'), ('santa_cruz_se', 'Santa Cruz-SE'), ('santo_antonio_es', 'Santo Antônio - ES'), ('juventus_sp', 'Juventus-SP'), ('catuense_ba', 'Catuense-BA'), ('nova_hamburgo_rs', 'Nova Hamburgo-RS'), ('asa_de_arapiraca', 'ASA de Arapiraca'), ('brasiliense', 'Brasiliense'), ('operario_pr', 'Operário-PR'), ('itumbiara_go', 'Itumbiara-GO'), ('taguatinga_df', 'Taguatinga-DF'), ('ipatinga_mg', 'Ipatinga-MG'), ('noroeste_sp', 'Noroeste-SP'), ('sao_bento_sp', 'São Bento-SP'), ('anapolis_go', 'Anápolis-GO'), ('vitoria_es', 'Vitória-ES'), ('ferroviaria_sp', 'Ferroviária-SP'), ('colatina_es', 'Colatina-ES'), ('guara_df', 'Guará-DF'), ('sobradinho_df', 'Sobradinho-DF'), ('cuiaba_mt', 'Cuiabá-MT'), ('inter_de_santa_maria_rs', 'Inter de Santa Maria-RS'), ('auto_esporte_pb', 'Auto Esporte-PB'), ('j_malucelli_pr', 'J. Malucelli-PR'), ('caldense', 'Caldense'), ('corumbaense', 'Corumbaense'), ('auto_esporte_pi', 'Auto Esporte-PI'), ('ferroviario_ma', 'Ferroviário-MA'), ('potiguar_de_mossoro_rn', 'Potiguar de Mossoró-RN'), ('francana_sp', 'Francana-SP'), ('america_de_propria_se', 'América de Própria-SE'), ('rio_branco_rj', 'Rio Branco-RJ'), ('inter_de_lages_sc', 'Inter de Lages-SC'), ('hercilio_luz_sc', 'Hercílio Luz-SC'), ('agua_verde_pr', 'Agua Verde-PR'), ('america_ce', 'América-CE'), ('comercial_pr', 'Comercial-PR'), ('defele_df', 'Defelê-DF'), ('cruzeiro_do_sul_df', 'Cruzeiro do Sul-DF'), ('eletrovapo_rj', 'Eletrovapo-RJ'), ('estrela_do_mar_pb', 'Estrela do Mar-PB'), ('guanabara_df', 'Guanabara-DF'), ('manufatora_rj', 'Manufatora-RJ'), ('olimpico_am', 'Olímpico-AM'), ('olimpico_sc', 'Olímpico - SC'), ('paula_ramos_sc', 'Paula Ramos-SC'), ('perdigao_sc', 'Perdigão-SC'), ('siderurgica_mg', 'Siderúrgica-MG')], max_length=50, null=True)),
                ('gols_marcados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('partidas_jogadas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pontos', models.SmallIntegerField(blank=True, null=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
