# Generated by Django 4.2.1 on 2023-06-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('federado', 'Federado'), ('convidado', 'Convidado')], default='federado', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='gols_marcados',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='partidas_jogadas',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pontos',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
