# Generated by Django 4.2.1 on 2023-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='mensagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='texto_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
