# Generated by Django 4.2.1 on 2023-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='nome',
            field=models.CharField(default='', max_length=18),
        ),
    ]
