# Generated by Django 4.2.1 on 2023-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_configuracao_link_configuracao_mensagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracao',
            old_name='link',
            new_name='alerta_link',
        ),
        migrations.RenameField(
            model_name='configuracao',
            old_name='mensagem',
            new_name='alerta_mensagem',
        ),
        migrations.RenameField(
            model_name='configuracao',
            old_name='texto_link',
            new_name='alerta_texto_link',
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_cor',
            field=models.CharField(blank=True, choices=[('warning', 'Amarelo'), ('danger', 'Vermelho'), ('success', 'Verde'), ('dark', 'Preto'), ('primary', 'Azul'), ('info', 'Azul-Claro'), ('secondary', 'Cinza'), ('light', 'Branco')], default='warning', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_icon',
            field=models.CharField(blank=True, choices=[('<use xlink:href="#exclamation-triangle-fill"/>', 'Triângulo com Exclamação'), ('<use xlink:href="#info-fill"/>', 'Círculo com "i"'), ('<use xlink:href="#check-circle-fill"/>', 'Círculo com "check"')], default=None, max_length=50, null=True),
        ),
    ]
