# Generated by Django 4.2.1 on 2023-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patrocinador_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título:')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Notícia:')),
                ('imagem', models.ImageField(upload_to='main/images/noticias', verbose_name='Imagem:')),
                ('desc_imagem', models.CharField(max_length=100, verbose_name='Descrição da Imagem:')),
            ],
            options={
                'verbose_name': 'Noticía',
                'verbose_name_plural': 'Noticías',
            },
        ),
    ]
