# Generated by Django 4.2.1 on 2023-07-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_link_configuracao_alerta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_icon',
            field=models.CharField(blank=True, choices=[('#exclamation-triangle-fill', 'Triângulo com Exclamação'), ('#info-fill', 'Círculo com "i"'), ('#check-circle-fill', 'Círculo com "check"')], default=None, max_length=50, null=True),
        ),
    ]
