# Generated by Django 4.2.1 on 2023-07-18 13:53

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_configuracao_alerta_cor_configuracao_alerta_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='imagem',
        ),
        migrations.AddField(
            model_name='noticia',
            name='mídia',
            field=models.FileField(default='', upload_to=main.models.MediaTypeUploadTo(), validators=[main.models.validate_media_file], verbose_name='Imagem ou vídeo:'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='desc_imagem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição da Imagem:'),
        ),
    ]
