# Generated by Django 4.2.1 on 2023-07-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_noticia_imagem_noticia_mídia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='mídia',
            new_name='midia',
        ),
    ]
