# Generated by Django 4.2.1 on 2023-07-01 14:34

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('timeA', models.ManyToManyField(blank=True, related_name='partidas_timeA', to=settings.AUTH_USER_MODEL)),
                ('timeB', models.ManyToManyField(blank=True, related_name='partidas_timeB', to=settings.AUTH_USER_MODEL)),
                ('timeC', models.ManyToManyField(blank=True, related_name='partidas_timeC', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
