# Generated by Django 4.2.1 on 2023-07-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
