# Generated by Django 4.2.1 on 2023-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_noticia_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='duracao_video',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração do vídeo (em milissegundos):'),
        ),
    ]
