# Generated by Django 4.2.1 on 2023-07-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_partida_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='timeC',
            new_name='time_reserva',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='timeA',
            new_name='time_verde',
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='timeB',
            new_name='time_vermelho',
        ),
    ]
