# Generated by Django 4.2.1 on 2023-08-07 14:45

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_configuracao_options_configuracao_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_cor',
            field=models.CharField(blank=True, choices=[('warning', 'Amarelo'), ('danger', 'Vermelho'), ('success', 'Verde'), ('dark', 'Preto'), ('primary', 'Azul'), ('info', 'Azul-Claro'), ('secondary', 'Cinza'), ('light', 'Branco')], default='warning', max_length=50, null=True, verbose_name='Cor do Alerta:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_icon',
            field=models.CharField(blank=True, choices=[('#exclamation-triangle-fill', 'Triângulo com Exclamação'), ('#info-fill', 'Círculo com "i"'), ('#check-circle-fill', 'Círculo com "check"')], default=None, max_length=50, null=True, verbose_name='Ícone do Alerta:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Alerta:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_mensagem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mensagem do Alerta:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='alerta_texto_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do link do Alerta:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave pix para pagamentos:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='email_diretor',
            field=models.EmailField(max_length=254, verbose_name='E-mail do Diretor:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='qr_code_pagamento',
            field=models.ImageField(upload_to='main/images/', verbose_name='QR Para pagamentos:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='regras_federacao',
            field=models.TextField(verbose_name='Regras da Federação:'),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='telefone_diretor',
            field=models.CharField(max_length=100, verbose_name='Telefone do Diretor:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/pagamentos', verbose_name='Comprovante:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='em_dinheiro',
            field=models.BooleanField(default=False, verbose_name='Pagamento em dinheiro?:'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='data',
            field=models.DateField(null=True, verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Horário:'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='sorteada',
            field=models.BooleanField(default=False, verbose_name='Foi sorteada?'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='link',
            field=models.URLField(default='', verbose_name='Link:'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='logo',
            field=models.ImageField(upload_to='main/images/patrocinadores', verbose_name='Logo:'),
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='nome',
            field=models.CharField(default='', max_length=18, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidade_nascimento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade natal:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='main/foto_jogador', verbose_name='Foto principal:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='main/foto_jogador', verbose_name='Foto com colete:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gols_marcados',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Gols marcados:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Isso defino se o usuário é ativo no sistema.', verbose_name='Está ativo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Isso define se o usuário tem ou não acesso à esta administração do site.', verbose_name='É administrador?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_jogador',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nome de Jogador:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pontos',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Pontos:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='posicao',
            field=models.CharField(choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral', 'Lateral'), ('volante', 'Volante'), ('meia', 'Meia'), ('ponta', 'Ponta'), ('centroavante', 'Centroavante')], max_length=50, verbose_name='Posição:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve conter apenas números, hífens (-) e espaços.', regex='^[0-9\\- ]*$')], verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_coracao',
            field=models.CharField(blank=True, choices=[('gremio', 'Grêmio'), ('santos', 'Santos'), ('cruzeiro', 'Cruzeiro'), ('palmeiras', 'Palmeiras'), ('atletico_mineiro', 'Atlético Mineiro'), ('botafogo', 'Botafogo'), ('flamengo', 'Flamengo'), ('fluminense', 'Fluminense'), ('internacional', 'Internacional'), ('sao_paulo', 'São Paulo'), ('vasco_da_gama', 'Vasco da Gama'), ('corinthians', 'Corinthians'), ('bahia', 'Bahia'), ('athletico_paranaense', 'Athletico Paranaense'), ('sport', 'Sport'), ('goias', 'Goiás'), ('coritiba', 'Coritiba'), ('vitoria', 'Vitória'), ('portuguesa', 'Portuguesa'), ('nautico', 'Náutico'), ('guarani', 'Guarani'), ('paysandu', 'Paysandu'), ('ceara', 'Ceará'), ('santa_cruz', 'Santa Cruz'), ('ponte_preta', 'Ponte Preta'), ('fortaleza', 'Fortaleza'), ('csa', 'CSA'), ('america_rj', 'America-RJ'), ('america_mineiro', 'América Mineiro'), ('figueirense', 'Figueirense'), ('juventude', 'Juventude'), ('remo', 'Remo'), ('parana', 'Paraná'), ('nacional_am', 'Nacional-AM'), ('america_rn', 'América-RN'), ('desportiva_ferroviaria', 'Desportiva Ferroviária-ES'), ('abc', 'ABC'), ('criciuma', 'Criciúma'), ('joinville', 'Joinville'), ('sampaio_correa', 'Sampaio Corrêa'), ('atletico_goianiense', 'Atlético Goianiense'), ('sergipe', 'Sergipe'), ('rio_branco_es', 'Rio Branco-ES'), ('crb', 'CRB'), ('bragantino', 'Bragantino'), ('moto_club', 'Moto Club'), ('bangu', 'Bangu'), ('campinense', 'Campinense'), ('avai', 'Avaí'), ('operario_ms', 'Operário-MS'), ('vila_nova', 'Vila Nova'), ('treze', 'Treze'), ('chapecoense', 'Chapecoense'), ('americano_rj', 'Americano-RJ'), ('confianca', 'Confiança'), ('river_pi', 'River-PI'), ('mixto_mt', 'Mixto-MT'), ('londrina', 'Londrina'), ('sao_caetano_sp', 'São Caetano-SP'), ('rio_negro_am', 'Rio Negro-AM'), ('botafogo_pb', 'Botafogo-PB'), ('flamengo_pi', 'Flamengo-PI'), ('inter_de_limeira', 'Inter de Limeira'), ('brasilia', 'Brasília'), ('botafogo_sp', 'Botafogo-SP'), ('gama', 'Gama'), ('ferroviario_ce', 'Ferroviário-CE'), ('gremio_maringa', 'Grêmio Maringá'), ('uberaba_mg', 'Uberaba-MG'), ('goytacaz_rj', 'Goytacaz-RJ'), ('comercial_ms', 'Comercial-MS'), ('itabaiana_se', 'Itabaiana-SE'), ('tiradentes_pi', 'Tiradentes-PI'), ('tuna_luso', 'Tuna Luso'), ('anapolina', 'Anapolina'), ('caxias_do_sul', 'Caxias do Sul'), ('brasil_de_pelotas', 'Brasil de Pelotas'), ('uniao_sao_joao_sp', 'União São João-SP'), ('uberlandia', 'Uberlândia'), ('fluminense_de_feira', 'Fluminense de Feira'), ('ceov_mt', 'CEOV-MT'), ('goiania', 'Goiânia'), ('piaui', 'Piauí'), ('xv_de_piracicaba', 'XV de Piracicaba'), ('volta_redonda', 'Volta Redonda'), ('maranhao', 'Maranhão'), ('leonico_ba', 'Leônico-BA'), ('villa_nova_mg', 'Villa Nova-MG'), ('fast_clube_am', 'Fast Clube-AM'), ('alecrim_rn', 'Alecrim-RN'), ('sao_paulo_rs', 'São Paulo-RS'), ('dom_bosco_mt', 'Dom Bosco-MT'), ('ceub_df', 'CEUB-DF'), ('ferroviario_pr', 'Ferroviário-PR'), ('fonseca_rj', 'Fonseca-RJ'), ('rabello_df', 'Rabello-DF'), ('central_pe', 'Central-PE'), ('santo_andre', 'Santo André'), ('america_sp', 'América-SP'), ('campo_grande_rj', 'Campo Grande-RJ'), ('gremio_barueri', 'Grêmio Barueri'), ('pinheiros_pr', 'Pinheiros-PR'), ('sao_jose_sp', 'São José-SP'), ('itabuna_ba', 'Itabuna-BA'), ('comercial_sp', 'Comercial-SP'), ('glicia_ba', 'Galícia-BA'), ('capelense_al', 'Capelense-AL'), ('olaria_rj', 'Olaria-RJ'), ('xv_de_jau', 'XV de Jaú'), ('santa_cruz_se', 'Santa Cruz-SE'), ('santo_antonio_es', 'Santo Antônio - ES'), ('juventus_sp', 'Juventus-SP'), ('catuense_ba', 'Catuense-BA'), ('nova_hamburgo_rs', 'Nova Hamburgo-RS'), ('asa_de_arapiraca', 'ASA de Arapiraca'), ('brasiliense', 'Brasiliense'), ('operario_pr', 'Operário-PR'), ('itumbiara_go', 'Itumbiara-GO'), ('taguatinga_df', 'Taguatinga-DF'), ('ipatinga_mg', 'Ipatinga-MG'), ('noroeste_sp', 'Noroeste-SP'), ('sao_bento_sp', 'São Bento-SP'), ('anapolis_go', 'Anápolis-GO'), ('vitoria_es', 'Vitória-ES'), ('ferroviaria_sp', 'Ferroviária-SP'), ('colatina_es', 'Colatina-ES'), ('guara_df', 'Guará-DF'), ('sobradinho_df', 'Sobradinho-DF'), ('cuiaba_mt', 'Cuiabá-MT'), ('inter_de_santa_maria_rs', 'Inter de Santa Maria-RS'), ('auto_esporte_pb', 'Auto Esporte-PB'), ('j_malucelli_pr', 'J. Malucelli-PR'), ('caldense', 'Caldense'), ('corumbaense', 'Corumbaense'), ('auto_esporte_pi', 'Auto Esporte-PI'), ('ferroviario_ma', 'Ferroviário-MA'), ('potiguar_de_mossoro_rn', 'Potiguar de Mossoró-RN'), ('francana_sp', 'Francana-SP'), ('america_de_propria_se', 'América de Própria-SE'), ('rio_branco_rj', 'Rio Branco-RJ'), ('inter_de_lages_sc', 'Inter de Lages-SC'), ('hercilio_luz_sc', 'Hercílio Luz-SC'), ('agua_verde_pr', 'Agua Verde-PR'), ('america_ce', 'América-CE'), ('comercial_pr', 'Comercial-PR'), ('defele_df', 'Defelê-DF'), ('cruzeiro_do_sul_df', 'Cruzeiro do Sul-DF'), ('eletrovapo_rj', 'Eletrovapo-RJ'), ('estrela_do_mar_pb', 'Estrela do Mar-PB'), ('guanabara_df', 'Guanabara-DF'), ('manufatora_rj', 'Manufatora-RJ'), ('olimpico_am', 'Olímpico-AM'), ('olimpico_sc', 'Olímpico - SC'), ('paula_ramos_sc', 'Paula Ramos-SC'), ('perdigao_sc', 'Perdigão-SC'), ('siderurgica_mg', 'Siderúrgica-MG')], max_length=50, null=True, verbose_name='Time do Coração:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('federado', 'Federado'), ('convidado', 'Convidado')], default='federado', max_length=50, verbose_name='Tipo:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uf_nascimento',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, null=True, verbose_name='Estado natal:'),
        ),
    ]
