# Generated by Django 4.2.1 on 2023-07-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_patrocinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
