# Generated by Django 4.2.1 on 2023-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_partida_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='razao_anulacao',
            field=models.CharField(blank=True, max_length=155, verbose_name='Qual a razão da anulação?'),
        ),
    ]
