# Generated by Django 4.2.1 on 2023-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_partida_razao_anulacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='razao_anulacao',
            field=models.TextField(blank=True, verbose_name='Qual a razão da anulação?'),
        ),
    ]
