# Generated by Django 4.2.1 on 2023-07-03 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_convidado'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='federado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convidados', to=settings.AUTH_USER_MODEL),
        ),
    ]
