# Generated by Django 4.2.1 on 2023-07-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_convidado_federado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convidado',
        ),
    ]
