# Generated by Django 4.2.1 on 2023-08-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pagamento_data_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data e hora do pagamento'),
        ),
    ]
