# Generated by Django 4.2.1 on 2023-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_pagamento_data_hora_pagamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data do pagamento'),
        ),
    ]
