# Generated by Django 4.2.1 on 2023-07-04 00:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_convidado_options_alter_pagamento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.RemoveField(
            model_name='convidado',
            name='federado',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='convidados',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='time_reserva',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='time_verde',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='time_vermelho',
        ),
        migrations.CreateModel(
            name='PartidaJogadorVermelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
            options={
                'verbose_name': 'Jogador da Partida (Time Vermelho)',
                'verbose_name_plural': 'Jogadores das Partidas (Time Vermelho)',
            },
        ),
        migrations.CreateModel(
            name='PartidaJogadorVerde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
            options={
                'verbose_name': 'Jogador da Partida (Time Verde)',
                'verbose_name_plural': 'Jogadores das Partidas (Time Verde)',
            },
        ),
        migrations.CreateModel(
            name='PartidaJogadorReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
            options={
                'verbose_name': 'Jogador da Partida (Time Reserva)',
                'verbose_name_plural': 'Jogadores das Partidas (Time Reserva)',
            },
        ),
        migrations.AddField(
            model_name='convidado',
            name='jogador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convidado', to='main.jogador'),
        ),
        migrations.AddField(
            model_name='user',
            name='jogador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.jogador'),
        ),
    ]
