# Generated by Django 4.2.1 on 2023-07-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_partida_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
