# Generated by Django 4.2.1 on 2023-07-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_jogador_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='nome',
        ),
    ]
