# Generated by Django 4.2.1 on 2023-07-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_partida_time_reserva_partida_time_verde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmado',
        ),
    ]
