# Generated by Django 4.2.1 on 2023-07-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='partidas_jogadas',
        ),
    ]
