# Generated by Django 4.2.1 on 2023-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_user_partidas_jogadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='em_dinheiro',
            field=models.BooleanField(default=False),
        ),
    ]
