# Generated by Django 4.2.1 on 2023-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_pagamento_em_dinheiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.ImageField(null=True, upload_to='main/images/pagamentos'),
        ),
    ]
