# Generated by Django 4.0.6 on 2023-07-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_pagamento_comprovante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_diretor', models.CharField(max_length=100)),
                ('email_diretor', models.EmailField(max_length=254)),
                ('qr_code_pagamento', models.ImageField(upload_to='main/images/')),
                ('regras_federacao', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
