# Generated by Django 4.0.6 on 2023-07-07 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_configuracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='time_reserva',
            new_name='time_azul',
        ),
        migrations.AddField(
            model_name='partida',
            name='relacionados',
            field=models.ManyToManyField(blank=True, related_name='relacionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partida',
            name='sorteada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comprovante',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/pagamentos'),
        ),
    ]
