# Generated by Django 4.0.6 on 2023-07-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_time_reserva_partida_time_azul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='main/foto_jogador'),
        ),
    ]
