# Generated by Django 4.0.6 on 2023-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_user_foto_secundaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='alerta_cor',
            field=models.CharField(blank=True, choices=[('warning', 'Amarelo'), ('danger', 'Vermelho'), ('success', 'Verde'), ('dark', 'Preto'), ('primary', 'Azul'), ('info', 'Azul-Claro'), ('secondary', 'Cinza'), ('light', 'Branco')], default='warning', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_icon',
            field=models.CharField(blank=True, choices=[('#exclamation-triangle-fill', 'Triângulo com Exclamação'), ('#info-fill', 'Círculo com "i"'), ('#check-circle-fill', 'Círculo com "check"')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_mensagem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alerta_texto_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
