# Generated by Django 4.0.6 on 2023-07-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_configuracao_alerta_cor_configuracao_alerta_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='nome',
            field=models.CharField(default='', max_length=18),
        ),
    ]
