# Generated by Django 4.0.6 on 2023-07-18 16:21

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_patrocinador_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título:')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto da Notícia:')),
                ('midia', models.FileField(upload_to=main.models.MediaTypeUploadTo(), validators=[main.models.validate_media_file], verbose_name='Imagem ou vídeo:')),
                ('duracao_video', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração do vídeo (em milissegundos):')),
                ('desc_imagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição da Imagem:')),
            ],
            options={
                'verbose_name': 'Noticía',
                'verbose_name_plural': 'Noticías',
            },
        ),
    ]
