# Generated by Django 4.0.6 on 2023-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configurações', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AddField(
            model_name='configuracao',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
