# Generated by Django 4.0.6 on 2023-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_configuracao_alerta_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='anulada',
            field=models.BooleanField(default=False, verbose_name='Foi anulada?'),
        ),
        migrations.AddField(
            model_name='partida',
            name='razao_anulacao',
            field=models.TextField(blank=True, verbose_name='Qual a razão da anulação?'),
        ),
    ]
