# Generated by Django 4.2.1 on 2023-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_partida_anulada_partida_razao_anulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Pagamento confirmado?'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Valor do pagamento:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='em_dinheiro',
            field=models.BooleanField(default=False, verbose_name='Pagamento em dinheiro?'),
        ),
    ]
