# Generated by Django 4.0.6 on 2023-09-03 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_partida_anulada_partida_razao_anulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Pagamento confirmado?'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Pagamento:'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Valor do pagamento:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='em_dinheiro',
            field=models.BooleanField(default=False, verbose_name='Pagamento em dinheiro?'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
        ),
    ]
