# Generated by Django 4.2.1 on 2023-09-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_pagamento_confirmado_pagamento_data_pagamento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Pagamento:'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
        ),
    ]
