# Generated by Django 4.2.1 on 2023-09-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_pagamento_confirmado_pagamento_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
    ]
