# Generated by Django 4.2.5 on 2023-10-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='jogador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votos_feitos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='partida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.partida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voto',
            name='votou_em',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votos_recebidos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(verbose_name='Quantos gols?')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Gols',
            },
        ),
    ]
