# Generated by Django 4.2.1 on 2023-08-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da saída:')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da saída:')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('partida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partida', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
        ),
    ]
