# Generated by Django 4.2.1 on 2023-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição da saída:')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da saída:')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
        ),
    ]
