# Generated by Django 4.2.1 on 2023-08-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_partida_valor_aluguel'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.partida', verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição da saída:'),
        ),
    ]
