# Generated by Django 5.0.1 on 2024-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('main', '0045_alter_partida_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['descricao'], name='financeiro__descric_8acdec_idx'),
        ),
    ]
